### PR TITLE
Ome image chooser

### PR DESCRIPTION
**Pull request by imunro**
Use OMEuiUtils to load data from OMERO.

### CODE REVIEW

**Comment by joshmoore** [comment]
2 cents: pulling ome-ui-utils from artifactory would be a good next step. /cc @sbesson

**Comment by imunro** [comment]
@joshmoore Perhaps let people try FLIMfit, once this is working, & the team can decide if this is something they want to distribute.

**Comment by joshmoore** [comment]
Makes sense to me. I'm just in "anti-jars-in-git" mode. :smile:

**Comment by imunro** [comment]
I certainly wouldn't object if it got done by somebody.OTOH  I just have one  problem with multiple .jars in the class path to sort out ( & in the past sbesson has proved really helpful with these) before I'm happy for people ( gus, you, sbesson ??) to check it out & see what they think .

**Comment by imunro** [comment]
After some assistance from @sbesson this now works to my satisfaction (loading speed of OMEROImageChooser apart)  so @joshmoore if people want to decide on whether OMEuiUtils should be taken under the OME umbrella you can now use the FLIMfit latest builds to evaluate.

**Pull request merged**
